import { Message } from "./message";
import { Modal } from "./modal";
import { Attachments } from "./attachments";
import { MDSymbols } from "./mdsymbols";
import { ColouredText } from "./messaging/ColouredText";
import { LitMessageRenderer } from "./messaging/MessageRenderer";
import { Markdown } from "./messaging/Markdown";
import { Indicator } from "./ui/indicator";
import { BaseEmbed } from "./messaging/embed/baseEmbed";
import { ServerIcon } from "./ui/serverIcon";
import { ServerList } from "./ServerList";
import { SecondarySidebar } from "./ui/SecondarySidebar";
import { MessageView } from "./ui/MessageView";

customElements.define("message-renderer", Message);
customElements.define("markdown-renderer", Markdown);
customElements.define("embeded-content", BaseEmbed);
customElements.define("lit-message-renderer", LitMessageRenderer);
customElements.define("snackbar-indicator", Indicator);
customElements.define("attachment-renderer", Attachments);
customElements.define("material-symbols", MDSymbols);
customElements.define("coloured-text", ColouredText);
customElements.define("server-icon", ServerIcon);
customElements.define("server-list", ServerList);
customElements.define("secondary-list", SecondarySidebar);
customElements.define("message-view", MessageView);
customElements.define("custom-modal", Modal, { extends: "dialog" });
